/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "tests/test_transpone.checkmk" instead.
 */

#include "test.h"

START_TEST(trans_n1) {
  // OK with normal values
  matrix_t A;
  matrix_t result;
  s21_create_matrix(1, 4, &A);
  ck_assert_int_eq(s21_transpose(&A, &result), OK);
  matrix_t result_A;
  ck_assert_int_eq(s21_transpose(&result, &result_A), OK);
  ck_assert_int_eq(s21_eq_matrix(&A, &result_A), SUCCESS);
  s21_remove_matrix(&A);
  s21_remove_matrix(&result);
  s21_remove_matrix(&result_A);
}
END_TEST

START_TEST(trans_n2) {
  // failure with NULL value from result
  matrix_t A;
  s21_create_matrix(5, 5, &A);
  ck_assert_int_eq(s21_transpose(&A, NULL), INCORR_MATRIX_ERROR);
  s21_remove_matrix(&A);
}
END_TEST

START_TEST(trans_n3) {
  // failure with NULL value from A_argument
  matrix_t result;
  ck_assert_int_eq(s21_transpose(NULL, &result), INCORR_MATRIX_ERROR);
}
END_TEST

START_TEST(trans_n4) {
  // OK with normal value
  int is_null = 0;
  matrix_t A;
  matrix_t result;
  s21_create_matrix(4, 10, &A);
  s21_fill_matrix(&A, 1, 0);
  ck_assert_int_eq(s21_transpose(&A, &result), OK);
  for (int i = 0; i < 10; i++) {
    if (!result.matrix[i]) {
      is_null = 1;
      break;
    }
  }
  for (int i = 0; i < 4; i++) {
    if (result.matrix[0][i] != 1) {
      is_null = 1;
      break;
    }
  }

  ck_assert_int_eq(is_null, 0);
  s21_remove_matrix(&A);
  s21_remove_matrix(&result);
}
END_TEST

START_TEST(trans_n5) {
  // OK with normal value
  matrix_t A;
  matrix_t result;
  s21_create_matrix(1, 5, &A);
  A.matrix[0][0] = 1, A.matrix[0][1] = 2, A.matrix[0][2] = 3,
  A.matrix[0][3] = 4, A.matrix[0][4] = 5;
  ck_assert_int_eq(s21_transpose(&A, &result), OK);
  ck_assert_int_eq(result.matrix[0][0], 1);
  ck_assert_int_eq(result.matrix[1][0], 2);
  ck_assert_int_eq(result.matrix[2][0], 3);
  ck_assert_int_eq(result.matrix[3][0], 4);
  ck_assert_int_eq(result.matrix[4][0], 5);
  s21_remove_matrix(&A);
  s21_remove_matrix(&result);
}
END_TEST

int test_transopse_main(void) {
  Suite *s1 = suite_create("transpone tests");
  TCase *tc1_1 = tcase_create("transpone tests");
  SRunner *sr = srunner_create(s1);
  int nf;

  suite_add_tcase(s1, tc1_1);
  tcase_add_test(tc1_1, trans_n1);
  tcase_add_test(tc1_1, trans_n2);
  tcase_add_test(tc1_1, trans_n3);
  tcase_add_test(tc1_1, trans_n4);
  tcase_add_test(tc1_1, trans_n5);

  srunner_run_all(sr, CK_ENV);
  nf = srunner_ntests_failed(sr);
  srunner_free(sr);

  return nf == 0 ? 0 : 1;
}
