/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "tests/test_create_remove.checkmk" instead.
 */

// #include <check.h>

// #line 1 "tests/test_create_remove.checkmk"
// #include "../s21_matrix.h"
#include "test.h"

START_TEST(s21_create_matrix_n1) {
  // success creation
  matrix_t A;
  ck_assert_int_eq(s21_create_matrix(5, 5, &A), OK);
  s21_remove_matrix(&A);
}
END_TEST

START_TEST(s21_create_matrix_n2) {
  // failure null pointer
  ck_assert_int_eq(s21_create_matrix(5, 5, NULL), INCORR_MATRIX_ERROR);
}
END_TEST

START_TEST(s21_create_matrix_n3) {
  // failure incorrect rows/columns
  matrix_t A;
  ck_assert_int_eq(s21_create_matrix(5, 0, &A), INCORR_MATRIX_ERROR);
}
END_TEST

START_TEST(s21_remove_matrix_n1) {
  // success remove
  matrix_t A;
  s21_create_matrix(5, 5, &A);
  s21_remove_matrix(&A);
  ck_assert_ptr_null(A.matrix);
}
END_TEST

START_TEST(s21_remove_matrix_n2) {
  // failure handle null pointer
  s21_remove_matrix(NULL);
  ck_assert_int_eq(1, 1);
}
END_TEST

int test_create_remove_main(void) {
  Suite *s1 = suite_create("create and remove tests");
  TCase *tc1_1 = tcase_create("create and remove tests");
  SRunner *sr = srunner_create(s1);
  int nf;

  suite_add_tcase(s1, tc1_1);
  tcase_add_test(tc1_1, s21_create_matrix_n1);
  tcase_add_test(tc1_1, s21_create_matrix_n2);
  tcase_add_test(tc1_1, s21_create_matrix_n3);
  tcase_add_test(tc1_1, s21_remove_matrix_n1);
  tcase_add_test(tc1_1, s21_remove_matrix_n2);

  srunner_run_all(sr, CK_ENV);
  nf = srunner_ntests_failed(sr);
  srunner_free(sr);

  return nf == 0 ? 0 : 1;
}
