// /*
//  * DO NOT EDIT THIS FILE. Generated by checkmk.
//  * Edit the original source file "tests/test_multiplication.checkmk" instead.
//  */

#include "test.h"

START_TEST(s21_mult_number_1) {
  // failure with INCORR_MATRIX_ERROR
  matrix_t A;
  double number = 3.14;
  s21_create_matrix(3, 3, &A);
  s21_fill_matrix(&A, 1, 1);
  ck_assert_int_eq(s21_mult_number(&A, number, NULL), INCORR_MATRIX_ERROR);
  s21_remove_matrix(&A);
}
END_TEST

START_TEST(s21_mult_number_2) {
  // failure with non-finite input double
  matrix_t A;
  matrix_t result;
  double number = INFINITY;
  s21_create_matrix(3, 3, &A);
  s21_fill_matrix(&A, 1, 1);
  ck_assert_int_eq(s21_mult_number(&A, number, &result), MATH_ERROR);
  s21_remove_matrix(&A);
  s21_remove_matrix(&result);
}
END_TEST

START_TEST(s21_mult_number_3) {
  // failure with with the resulting non-finite
  matrix_t A;
  matrix_t result;
  double number = 3;
  s21_create_matrix(3, 3, &A);
  s21_fill_matrix(&A, 1, 1);
  A.matrix[2][2] = INFINITY;
  ck_assert_int_eq(s21_mult_number(&A, number, &result), MATH_ERROR);
  s21_remove_matrix(&A);
}
END_TEST

START_TEST(s21_mult_number_4) {
  // success with uninitialized values
  matrix_t A;
  matrix_t result;
  matrix_t eq_matrix;
  double number = 3;
  s21_create_matrix(3, 3, &A);
  s21_create_matrix(3, 3, &eq_matrix);
  ck_assert_int_eq(s21_mult_number(&A, number, &result), OK);
  ck_assert_int_eq(s21_eq_matrix(&result, &eq_matrix), SUCCESS);
  s21_remove_matrix(&A);
  s21_remove_matrix(&result);
  s21_remove_matrix(&eq_matrix);
}
END_TEST

START_TEST(s21_mult_number_5) {
  // success with initialized values
  matrix_t A;
  matrix_t result;
  matrix_t eq_matrix;
  double number = 3;
  s21_create_matrix(3, 3, &A);
  s21_fill_matrix(&A, 1, 1);
  s21_create_matrix(3, 3, &eq_matrix);
  s21_fill_matrix(&eq_matrix, 3, 3);
  ck_assert_int_eq(s21_mult_number(&A, number, &result), OK);
  ck_assert_int_eq(s21_eq_matrix(&result, &eq_matrix), SUCCESS);
  s21_remove_matrix(&A);
  s21_remove_matrix(&result);
  s21_remove_matrix(&eq_matrix);
}
END_TEST

START_TEST(s21_mult_number_6) {
  // success with task reference values
  matrix_t A;
  matrix_t result;
  matrix_t eq_matrix;
  double number = 2;
  s21_create_matrix(3, 3, &A);
  A.matrix[0][0] = 1, A.matrix[0][1] = 2, A.matrix[0][2] = 3;
  A.matrix[1][0] = 0, A.matrix[1][1] = 4, A.matrix[1][2] = 2;
  A.matrix[2][0] = 2, A.matrix[2][1] = 3, A.matrix[2][2] = 4;
  s21_create_matrix(3, 3, &eq_matrix);
  eq_matrix.matrix[0][0] = 2, eq_matrix.matrix[0][1] = 4,
  eq_matrix.matrix[0][2] = 6;
  eq_matrix.matrix[1][0] = 0, eq_matrix.matrix[1][1] = 8,
  eq_matrix.matrix[1][2] = 4;
  eq_matrix.matrix[2][0] = 4, eq_matrix.matrix[2][1] = 6,
  eq_matrix.matrix[2][2] = 8;
  ck_assert_int_eq(s21_mult_number(&A, number, &result), OK);
  ck_assert_int_eq(s21_eq_matrix(&result, &eq_matrix), SUCCESS);
  s21_remove_matrix(&A);
  s21_remove_matrix(&result);
  s21_remove_matrix(&eq_matrix);
}
END_TEST

START_TEST(s21_mult_number1) {
  double number = 0;
  int rows = 10;
  int columns = 20;
  matrix_t A;
  matrix_t R;
  matrix_t C;
  s21_create_matrix(rows, columns, &A);
  s21_create_matrix(rows, columns, &C);
  s21_fill_matrix(&A, 100, 1);
  s21_fill_matrix(&C, 0, 0);
  int ret = s21_mult_number(&A, number, &R);
  int res = s21_eq_matrix(&C, &R);
  ck_assert_int_eq(OK, ret);
  ck_assert_int_eq(SUCCESS, res);
  s21_remove_matrix(&A);
  s21_remove_matrix(&R);
  s21_remove_matrix(&C);
}
END_TEST

START_TEST(s21_mult_number2) {
  double number = (rand() % 100 + 1) / 3;
  int rows = rand() % 100 + 1;
  int columns = rand() % 100 + 1;
  matrix_t A = {0};
  matrix_t R = {0};
  matrix_t C = {0};
  s21_create_matrix(rows, columns, &A);
  s21_create_matrix(rows, columns, &C);
  for (int i = 0; i < rows; i++) {
    for (int j = 0; j < columns; j++) {
      double t = rand();
      A.matrix[i][j] = t / 2;
      C.matrix[i][j] = number * A.matrix[i][j] * 2;
    }
  }
  int ret = s21_mult_number(&A, number, &R);
  int res = s21_eq_matrix(&C, &R);
  ck_assert_int_eq(OK, ret);
  ck_assert_int_eq(FAILURE, res);
  s21_remove_matrix(&A);
  s21_remove_matrix(&R);
  s21_remove_matrix(&C);
}
END_TEST

START_TEST(s21_mult_number3) {
  double number = (rand() % 100 + 1) / 3;
  int rows = 0;
  int columns = rand() % 100 + 1;
  matrix_t A = {0};
  matrix_t R = {0};
  s21_create_matrix(rows, columns, &A);
  int ret = s21_mult_number(&A, number, &R);
  ck_assert_int_eq(1, ret);
  s21_remove_matrix(&A);
  s21_remove_matrix(&R);
}
END_TEST

START_TEST(s21_mult_matrix_1) {
  // failure with INCORR_MATRIX_ERROR
  matrix_t A;
  s21_create_matrix(3, 3, &A);
  s21_fill_matrix(&A, 1, 1);
  ck_assert_int_eq(s21_mult_matrix(&A, NULL, NULL), INCORR_MATRIX_ERROR);
  s21_remove_matrix(&A);
}
END_TEST

START_TEST(s21_mult_matrix_2) {
  // failure with with the resulting non-finite
  matrix_t A;
  matrix_t B;
  matrix_t result;
  s21_create_matrix(3, 3, &A);
  s21_create_matrix(3, 3, &B);
  s21_fill_matrix(&A, 1, 1);
  B.matrix[2][2] = INFINITY;
  ck_assert_int_eq(s21_mult_matrix(&A, &B, &result), MATH_ERROR);
  s21_remove_matrix(&A);
  s21_remove_matrix(&B);
}
END_TEST

START_TEST(s21_mult_matrix_3) {
  // failure with different dimensions of matrices
  matrix_t A;
  matrix_t B;
  matrix_t result;
  s21_create_matrix(3, 2, &A);
  s21_create_matrix(3, 2, &B);
  ck_assert_int_eq(s21_mult_matrix(&A, &B, &result), MATH_ERROR);
  s21_remove_matrix(&A);
  s21_remove_matrix(&B);
}
END_TEST

START_TEST(s21_mult_matrix_4) {
  // success with uninitialized values
  matrix_t A;
  matrix_t B;
  matrix_t result;
  matrix_t eq_matrix;
  s21_create_matrix(3, 3, &A);
  s21_create_matrix(3, 3, &B);
  s21_create_matrix(3, 3, &eq_matrix);
  ck_assert_int_eq(s21_mult_matrix(&A, &B, &result), OK);
  ck_assert_int_eq(s21_eq_matrix(&result, &eq_matrix), SUCCESS);
  s21_remove_matrix(&A);
  s21_remove_matrix(&B);
  s21_remove_matrix(&result);
  s21_remove_matrix(&eq_matrix);
}
END_TEST

START_TEST(s21_mult_matrix_5) {
  // success with initialized values
  matrix_t A;
  matrix_t B;
  matrix_t result;
  matrix_t eq_matrix;
  s21_create_matrix(3, 3, &A);
  s21_fill_matrix(&A, 1, 1);
  s21_create_matrix(3, 3, &B);
  s21_fill_matrix(&B, 1, 1);
  s21_create_matrix(3, 3, &eq_matrix);
  eq_matrix.matrix[0][0] = 30, eq_matrix.matrix[0][1] = 36,
  eq_matrix.matrix[0][2] = 42;
  eq_matrix.matrix[1][0] = 66, eq_matrix.matrix[1][1] = 81,
  eq_matrix.matrix[1][2] = 96;
  eq_matrix.matrix[2][0] = 102, eq_matrix.matrix[2][1] = 126,
  eq_matrix.matrix[2][2] = 150;
  ck_assert_int_eq(s21_mult_matrix(&A, &B, &result), OK);
  ck_assert_int_eq(s21_eq_matrix(&result, &eq_matrix), SUCCESS);
  s21_remove_matrix(&A);
  s21_remove_matrix(&B);
  s21_remove_matrix(&result);
  s21_remove_matrix(&eq_matrix);
}
END_TEST

START_TEST(s21_mult_matrix_6) {
  // success with task reference values
  matrix_t A;
  matrix_t B;
  matrix_t result;
  matrix_t eq;
  s21_create_matrix(3, 2, &A);
  A.matrix[0][0] = 1, A.matrix[0][1] = 4;
  A.matrix[1][0] = 2, A.matrix[1][1] = 5;
  A.matrix[2][0] = 3, A.matrix[2][1] = 6;
  s21_create_matrix(2, 3, &B);
  B.matrix[0][0] = 1, B.matrix[0][1] = -1, B.matrix[0][2] = 1;
  B.matrix[1][0] = -2, B.matrix[1][1] = 3, B.matrix[1][2] = 4;
  s21_create_matrix(3, 3, &eq);
  eq.matrix[0][0] = -7, eq.matrix[0][1] = 11, eq.matrix[0][2] = 17;
  eq.matrix[1][0] = -8, eq.matrix[1][1] = 13, eq.matrix[1][2] = 22;
  eq.matrix[2][0] = -9, eq.matrix[2][1] = 15, eq.matrix[2][2] = 27;
  ck_assert_int_eq(s21_mult_matrix(&A, &B, &result), OK);
  ck_assert_int_eq(s21_eq_matrix(&result, &eq), SUCCESS);
  s21_remove_matrix(&A);
  s21_remove_matrix(&B);
  s21_remove_matrix(&result);
  s21_remove_matrix(&eq);
}
END_TEST

START_TEST(s21_mult_matrix1) {
  int rowsA = 2;
  int columnsA = 1;
  int columnsB = 2;
  matrix_t A = {0};
  matrix_t B = {0};
  matrix_t R = {0};
  matrix_t C = {0};
  s21_create_matrix(rowsA, columnsA, &A);
  s21_create_matrix(columnsA, columnsB, &B);
  s21_create_matrix(rowsA, columnsB, &C);
  for (int i = 0; i < rowsA; i++) {
    for (int j = 0; j < columnsA; j++) {
      A.matrix[i][j] = i + 2;
    }
  }

  for (int i = 0; i < columnsA; i++) {
    for (int j = 0; j < columnsB; j++) {
      B.matrix[i][j] = j + 1;
    }
  }

  C.matrix[0][0] = 2;
  C.matrix[0][1] = 4;
  C.matrix[1][0] = 3;
  C.matrix[1][1] = 6;
  int ret = s21_mult_matrix(&A, &B, &R);
  int res = s21_eq_matrix(&C, &R);
  ck_assert_int_eq(0, ret);
  ck_assert_int_eq(SUCCESS, res);
  s21_remove_matrix(&A);
  s21_remove_matrix(&B);
  s21_remove_matrix(&R);
  s21_remove_matrix(&C);
}
END_TEST

START_TEST(s21_mult_matrix2) {
  int rowsA = rand() % 100 + 1;
  int columnsA = rand() % 100 + 1;
  int columnsB = rand() % 100 + 1;
  matrix_t A = {0};
  matrix_t B = {0};
  matrix_t R = {0};
  matrix_t C = {0};
  s21_create_matrix(rowsA, columnsA, &A);
  s21_create_matrix(columnsA, columnsB, &B);
  s21_create_matrix(rowsA, columnsB, &C);
  for (int i = 0; i < rowsA; i++) {
    for (int j = 0; j < columnsA; j++) {
      double t = rand();
      A.matrix[i][j] = t / 3;
    }
  }
  for (int i = 0; i < columnsA; i++) {
    for (int j = 0; j < columnsB; j++) {
      double t = rand();
      B.matrix[i][j] = t / 5;
    }
  }
  for (int i = 0; i < C.rows; i++) {
    for (int j = 0; j < C.columns; j++) {
      for (int k = 0; k < A.columns; k++) {
        C.matrix[i][j] += A.matrix[i][k] * B.matrix[k][j];
      }
    }
  }
  int ret = s21_mult_matrix(&A, &B, &R);
  int res = s21_eq_matrix(&C, &R);
  ck_assert_int_eq(0, ret);
  ck_assert_int_eq(SUCCESS, res);
  s21_remove_matrix(&A);
  s21_remove_matrix(&B);
  s21_remove_matrix(&R);
  s21_remove_matrix(&C);
}
END_TEST

START_TEST(s21_mult_matrix3) {
  int rowsA = rand() % 100 + 1;
  int columnsA = rand() % 100 + 1;
  int columnsB = rand() % 100 + 1;
  matrix_t A = {0};
  matrix_t B = {0};
  matrix_t R = {0};
  matrix_t C = {0};
  s21_create_matrix(rowsA, columnsA, &A);
  s21_create_matrix(columnsA, columnsB, &B);
  s21_create_matrix(rowsA, columnsB, &C);
  for (int i = 0; i < rowsA; i++) {
    for (int j = 0; j < columnsA; j++) {
      double t = rand();
      A.matrix[i][j] = t / 3;
    }
  }
  for (int i = 0; i < columnsA; i++) {
    for (int j = 0; j < columnsB; j++) {
      double t = rand();
      B.matrix[i][j] = t / 5;
    }
  }
  int temp = 0;
  for (int i = 0; i < C.rows; i++) {
    for (int j = 0; j < C.columns; j++) {
      for (int k = 0; k < A.columns; k++) {
        temp = A.matrix[i][k] * B.matrix[k][j] + 10;
        C.matrix[i][j] += temp;
      }
    }
  }
  int ret = s21_mult_matrix(&A, &B, &R);
  int res = s21_eq_matrix(&C, &R);
  ck_assert_int_eq(0, ret);
  ck_assert_int_eq(FAILURE, res);
  s21_remove_matrix(&A);
  s21_remove_matrix(&B);
  s21_remove_matrix(&R);
  s21_remove_matrix(&C);
}
END_TEST

START_TEST(s21_mult_matrix4) {
  int rowsA = rand() % 100 + 1;
  int columnsA = rand() % 100 + 1;
  int columnsB = rand() % 100 + 1;
  matrix_t A = {0};
  matrix_t B = {0};
  matrix_t R = {0};
  s21_create_matrix(rowsA, columnsA, &A);
  s21_create_matrix(columnsA + 1, columnsB, &B);
  int ret = s21_mult_matrix(&A, &B, &R);
  ck_assert_int_eq(2, ret);
  s21_remove_matrix(&A);
  s21_remove_matrix(&B);
}
END_TEST

START_TEST(s21_mult_matrix5) {
  int rowsA = 0;
  int columnsA = rand() % 100 + 1;
  int columnsB = rand() % 100 + 1;
  matrix_t A = {0};
  matrix_t B = {0};
  matrix_t R = {0};
  s21_create_matrix(rowsA, columnsA, &A);
  s21_create_matrix(columnsA, columnsB, &B);
  int ret = s21_mult_matrix(&A, &B, &R);
  ck_assert_int_eq(1, ret);
  s21_remove_matrix(&A);
  s21_remove_matrix(&B);
}
END_TEST

START_TEST(s21_mult_matrix6) {
  int rowsA = 0;
  int columnsA = rand() % 100 + 1;
  int columnsB = rand() % 100 + 1;
  matrix_t A = {0};
  matrix_t B = {0};
  s21_create_matrix(rowsA, columnsA, &A);
  s21_create_matrix(columnsA, columnsB, &B);
  int ret = s21_mult_matrix(&A, &B, NULL);
  ck_assert_int_eq(1, ret);
  s21_remove_matrix(&A);
  s21_remove_matrix(&B);
}
END_TEST

int test_mult_main(void) {
  Suite *s1 = suite_create("mult num tests");
  TCase *tc1_1 = tcase_create("mult num tests");
  Suite *s2 = suite_create("mult matrix tests");
  TCase *tc2_1 = tcase_create("mult matrix tests");
  SRunner *sr = srunner_create(s1);
  int nf;

  suite_add_tcase(s1, tc1_1);
  tcase_add_test(tc1_1, s21_mult_number_1);
  tcase_add_test(tc1_1, s21_mult_number_2);
  tcase_add_test(tc1_1, s21_mult_number_3);
  tcase_add_test(tc1_1, s21_mult_number_4);
  tcase_add_test(tc1_1, s21_mult_number_5);
  tcase_add_test(tc1_1, s21_mult_number_6);
  tcase_add_test(tc1_1, s21_mult_number1);
  tcase_add_test(tc1_1, s21_mult_number2);
  tcase_add_test(tc1_1, s21_mult_number3);
  suite_add_tcase(s2, tc2_1);
  tcase_add_test(tc2_1, s21_mult_matrix_1);
  tcase_add_test(tc2_1, s21_mult_matrix_2);
  tcase_add_test(tc2_1, s21_mult_matrix_3);
  tcase_add_test(tc2_1, s21_mult_matrix_4);
  tcase_add_test(tc2_1, s21_mult_matrix_5);
  tcase_add_test(tc2_1, s21_mult_matrix_6);
  tcase_add_test(tc2_1, s21_mult_matrix1);
  tcase_add_test(tc2_1, s21_mult_matrix2);
  tcase_add_test(tc2_1, s21_mult_matrix3);
  tcase_add_test(tc2_1, s21_mult_matrix4);
  tcase_add_test(tc2_1, s21_mult_matrix5);
  tcase_add_test(tc2_1, s21_mult_matrix6);

  srunner_add_suite(sr, s2);

  srunner_run_all(sr, CK_ENV);
  nf = srunner_ntests_failed(sr);
  srunner_free(sr);

  return nf == 0 ? 0 : 1;
}
